name: Continuous Delivery

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Deploy the code to Cloud Functions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: GCP Auth
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - id: Deploy
        uses: xylo04/github-actions/cloudfunctions-deploy@master
        with:
          name: Hello
          entry_point: Hello
          project_id: random-stuff-292920
